import SwiftUI

struct ContentView: View {
    var body: some View {
        NavigationStack {
            List {
                Section {
                    ForEach(Array(User.edgeCases.enumerated()), id: \.offset) { index, user in
                        NavigationLink(value: index) {
                            VStack(alignment: .leading, spacing: 2) {
                                Text(user.displayName)
                                    .font(.headline)
                                Text("id \(user.id) · karma \(user.formattedKarma) · \(user.membershipLabel) · \(user.tagSummary)")
                                    .font(.caption)
                                    .foregroundStyle(.secondary)
                                    .lineLimit(1)
                            }
                        }
                    }
                } header: {
                    Text("\(User.edgeCases.count) generated edge cases")
                } footer: {
                    Text("Every instance in this list was generated by @EdgeCases — no hand-written fixtures. Tap one to see how the UI copes with it.")
                }
            }
            .navigationTitle("EdgeCase")
            .navigationDestination(for: Int.self) { index in
                UserDetailView(user: User.edgeCases[index])
            }
        }
    }
}

#Preview {
    ContentView()
}
